### ISSUE TITLE
Make struct immutable

### ISSUE THREAD

**Issue by aloisdg** [aloisdg/Licorne#13]
[see](http://stackoverflow.com/questions/6063212/does-using-public-readonly-fields-for-immutable-structs-work)

**Comment by aloisdg** [comment]
Thank you @deccer

reading:
- http://stackoverflow.com/questions/26078439/c-sharp-getter-vs-readonly
- http://programmers.stackexchange.com/questions/72495/net-properties-use-private-set-or-readonly-property
- http://qnundrum.com/question/851704

**Comment by deccer** [comment]
@aloisdg I just found this mention, no idea what I did there? :D Sorry for commenting on this closed item.
